In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from census import Census

## base_url = https://api.census.gov/data/2019/acs/acs5/subject?get=NAME,S0101_C01_001E&for=region:*&key=api_key

api_key = "0e395bcf9cca78932f9c8e80c0a8a55fe1cba723"
# Census API Key

c = Census(api_key, year=2019)

## "0e395bcf9cca78932f9c8e80c0a8a55fe1cba723"

# STATE CODES:
# 04|AZ|Arizona|01779777
# 06|CA|California|01779778
# 08|CO|Colorado|01779779
# 16|ID|Idaho|01779783
# 30|MT|Montana|00767982
# 32|NV|Nevada|01779793
# 35|NM|New Mexico|00897535
# 41|OR|Oregon|01155107
# 49|UT|Utah|01455989
# 53|WA|Washington|01779804
# 56|WY|Wyoming|01779807

In [10]:
census_data = c.acs5.get(("NAME", "B01003_001E", "B19013_001E", "B01003_001E", "B01002_001E", "B11001_001E",
                          "B19301_001E", "B08303_001E", "B08015_001E",
                          "B17001_002E"), {'for': 'zip code tabulation area:*'})

# # Convert to DataFrame
census_pd = pd.DataFrame(census_data)
census_pd.head()

,NAME,B01003_001E,B19013_001E,B01002_001E,B11001_001E,B19301_001E,B08303_001E,B08015_001E,B17001_002E,state,zip code tabulation area
0,ZCTA5 00601,17113.0,14361.0,41.9,5509.0,7493.0,3504.0,3115.0,10552.0,72,00601
1,ZCTA5 00602,37751.0,16807.0,42.9,12740.0,9694.0,10525.0,8645.0,18653.0,72,00602
2,ZCTA5 00603,47081.0,16049.0,42.1,19228.0,11259.0,11479.0,10460.0,23691.0,72,00603
3,ZCTA5 00606,6392.0,12119.0,44.3,1946.0,6093.0,1228.0,1085.0,4185.0,72,00606
4,ZCTA5 00610,26686.0,19898.0,42.7,8795.0,10572.0,8065.0,6800.0,12204.0,72,00610

In [17]:
# Column Reordering
census_pd = census_pd.rename(columns={"NAME": "State",
                                      "state": "State",
                                      "B01003_001E": "Population",
                                      "B11001_001E": "Number of Households",
                                      "B19013_001E": "Household Income",
#                                       "B19301_001E": "Per Capita Income",
                                      "B17001_002E": "Poverty Count",
                                      "B08303_001E": "Total Commute Time",
                                      "B08015_001E": "Total Vehicles",
                                      "NAME": "Name", "zip code tabulation area": "Zipcode"})



census_pd.head()

,State,Zipcode,Population,Number of Households,Household Income,Poverty Count,Poverty Rate,Total Commute Time,Average Commute Time,Total Vehicles,Average Vehicles per Household
0,72,00601,17113.0,5509.0,14361.0,10552.0,61.660726,3504.0,0.636050,3115.0,0.565438
1,72,00602,37751.0,12740.0,16807.0,18653.0,49.410612,10525.0,0.826138,8645.0,0.678571
2,72,00603,47081.0,19228.0,16049.0,23691.0,50.319662,11479.0,0.596994,10460.0,0.543998
3,72,00606,6392.0,1946.0,12119.0,4185.0,65.472466,1228.0,0.631038,1085.0,0.557554
4,72,00610,26686.0,8795.0,19898.0,12204.0,45.731844,8065.0,0.916998,6800.0,0.773167

In [18]:
census_pd["Poverty Rate"] = 100 * \
    census_pd["Poverty Count"].astype(
        int) / census_pd["Population"].astype(int)

census_pd["Average Vehicles per Household"] = census_pd["Total Vehicles"] / census_pd["Number of Households"]

census_pd["Average Commute Time"] = census_pd["Total Commute Time"] / census_pd["Number of Households"]

census_pd = census_pd[["State", "Zipcode", "Population", "Number of Households", 
                       "Household Income", "Poverty Count", "Poverty Rate", 
                       "Total Commute Time", "Average Commute Time",
                       "Total Vehicles", "Average Vehicles per Household"]]

# Visualize
print(len(census_pd))
census_pd.head()

33120

,State,Zipcode,Population,Number of Households,Household Income,Poverty Count,Poverty Rate,Total Commute Time,Average Commute Time,Total Vehicles,Average Vehicles per Household
0,72,00601,17113.0,5509.0,14361.0,10552.0,61.660726,3504.0,0.636050,3115.0,0.565438
1,72,00602,37751.0,12740.0,16807.0,18653.0,49.410612,10525.0,0.826138,8645.0,0.678571
2,72,00603,47081.0,19228.0,16049.0,23691.0,50.319662,11479.0,0.596994,10460.0,0.543998
3,72,00606,6392.0,1946.0,12119.0,4185.0,65.472466,1228.0,0.631038,1085.0,0.557554
4,72,00610,26686.0,8795.0,19898.0,12204.0,45.731844,8065.0,0.916998,6800.0,0.773167

In [ ]:
census_pd.to_csv("census_data.csv", encoding="utf-8", index=False

In [31]:
az_census = census_pd.loc[census_pd["State"]== "04"]

ca_census = census_pd.loc[census_pd["State"]== "06"]

co_census = census_pd.loc[census_pd["State"]== "08"]

id_census = census_pd.loc[census_pd["State"]== "16"]

mt_census = census_pd.loc[census_pd["State"]== "30"]

nv_census = census_pd.loc[census_pd["State"]== "32"]

nm_census = census_pd.loc[census_pd["State"]== "35"]

or_census = census_pd.loc[census_pd["State"]== "41"]

ut_census = census_pd.loc[census_pd["State"]== "49"]

wa_census = census_pd.loc[census_pd["State"]== "53"]

wy_census = census_pd.loc[census_pd["State"]== "56"]

state_census = [[az_census, ca_census, co_census, 
                    id_census, mt_census, nv_census, 
                    nm_census, or_census, ut_census, 
                    wa_census, wy_census]]
state_census

[[      State Zipcode  Population  Number of Households  Household Income  \
  29062    04   85003      8499.0                4101.0           44140.0
  29063    04   85004      7164.0                3017.0           41951.0
  29064    04   85006     27206.0                9355.0           38121.0
  29065    04   85007     14428.0                5287.0           34667.0
  29066    04   85008     62340.0               22404.0           43574.0
  ...     ...     ...         ...                   ...               ...
  29462    04   86540      1120.0                 268.0           10588.0
  29463    04   86544      1307.0                 327.0           26964.0
  29464    04   86545      1469.0                 407.0           22560.0
  29465    04   86547      1175.0                 272.0           24643.0
  29466    04   86556      2324.0                 513.0           27153.0

         Poverty Count  Poverty Rate  Total Commute Time  Average Commute Time  \
  29062         1544.0     18.166843              3911.0              0.953670
  29063         1918.0     26.772753              3602.0              1.193901
  29064         9530.0     35.029038             12076.0              1.290861
  29065         4672.0     32.381480              5717.0              1.081332
  29066        14866.0     23.846647             32156.0              1.435279
  ...              ...           ...                 ...                   ...
  29462          675.0     60.267857               154.0              0.574627
  29463          482.0     36.878347               310.0              0.948012
  29464          666.0     45.336964               270.0              0.663391
  29465          495.0     42.127660               217.0              0.797794
  29466          851.0     36.617900               541.0              1.054581

         Total Vehicles  Average Vehicles per Household
  29062          3010.0                        0.733967
  29063          2575.0                        0.853497
  29064          9745.0                        1.041689
  29065          4600.0                        0.870059
  29066         25395.0                        1.133503
  ...               ...                             ...
  29462           140.0                        0.522388
  29463           295.0                        0.902141
  29464           225.0                        0.552826
  29465           210.0                        0.772059
  29466           390.0                        0.760234

  [405 rows x 11 columns],
        State Zipcode  Population  Number of Households  Household Income  \
  30010    06   90001     59832.0               13669.0           43360.0
  30011    06   90002     53302.0               12917.0           37285.0
  30012    06   90003     73730.0               17484.0           40598.0
  30013    06   90004     60541.0               22004.0           49675.0
  30014    06   90005     39732.0               16781.0           38491.0
  ...     ...     ...         ...                   ...               ...
  31769    06   96148       580.0                 214.0           73611.0
  31770    06   96150     29327.0               11767.0           57396.0
  31771    06   96155         0.0                   0.0      -666666666.0
  31772    06   96161     18488.0                6927.0           98924.0
  32180    06   97635       170.0                  85.0      -666666666.0

         Poverty Count  Poverty Rate  Total Commute Time  Average Commute Time  \
  30010        15255.0     25.496390             23461.0              1.716365
  30011        16624.0     31.188323             19509.0              1.510335
  30012        22089.0     29.959311             28363.0              1.622226
  30013        10767.0     17.784642             31079.0              1.412425
  30014        10330.0     25.999195             20474.0              1.220070
  ...              ...           ...                 ...                   ...
  31769          121.0     20.862069               313.0              1.462617
  31770         3172.0     10.815972             14113.0              1.199371
  31771            0.0           NaN                 0.0                   NaN
  31772         1565.0      8.464950              8846.0              1.277032
  32180           59.0     34.705882                33.0              0.388235

         Total Vehicles  Average Vehicles per Household
  30010         17620.0                        1.289048
  30011         14705.0                        1.138422
  30012         21755.0                        1.244280
  30013         22640.0                        1.028904
  30014         12080.0                        0.719862
  ...               ...                             ...
  31769           305.0                        1.425234
  31770         11330.0                        0.962862
  31771    -666666666.0                            -inf
  31772          7700.0                        1.111592
  32180             NaN                             NaN

  [1764 rows x 11 columns],
        State Zipcode  Population  Number of Households  Household Income  \
  27793    08   80002     18877.0                8346.0           63745.0
  27794    08   80003     36480.0               14301.0           66114.0
  27795    08   80004     36595.0               14863.0           78586.0
  27796    08   80005     28737.0               11078.0          107300.0
  27797    08   80007     13783.0                4849.0          147421.0
  ...     ...     ...         ...                   ...               ...
  28313    08   81653         9.0                   9.0      -666666666.0
  28314    08   81654      1487.0                 543.0           54535.0
  28315    08   81655        77.0                  11.0      -666666666.0
  28316    08   81656       223.0                 124.0      -666666666.0
  28317    08   81657      5847.0                2382.0           83571.0

         Poverty Count  Poverty Rate  Total Commute Time  Average Commute Time  \
  27793         2389.0     12.655613             10242.0              1.227175
  27794         3178.0      8.711623             18621.0              1.302077
  27795         2316.0      6.328733             17563.0              1.181659
  27796          781.0      2.717751             14106.0              1.273335
  27797           93.0      0.674744              6587.0              1.358424
  ...              ...           ...                 ...                   ...
  28313            9.0    100.000000                 0.0              0.000000
  28314           53.0      3.564223               737.0              1.357274
  28315            0.0      0.000000                47.0              4.272727
  28316           23.0     10.313901                92.0              0.741935
  28317          506.0      8.654011              3623.0              1.520991

         Total Vehicles  Average Vehicles per Household
  27793          9100.0                    1.090343e+00
  27794         17085.0                    1.194672e+00
  27795         16005.0                    1.076835e+00
  27796         12790.0                    1.154541e+00
  27797          5995.0                    1.236337e+00
  ...               ...                             ...
  28313    -666666666.0                   -7.407407e+07
  28314           670.0                    1.233886e+00
  28315             NaN                             NaN
  28316             NaN                             NaN
  28317          2780.0                    1.167086e+00

  [525 rows x 11 columns],
        State Zipcode  Population  Number of Households  Household Income  \
  28495    16   83201     38506.0               13971.0           50526.0
  28496    16   83202     22714.0                7701.0           56977.0
  28497    16   83203       278.0                 120.0           29688.0
  28498    16   83204     18761.0                7379.0           45187.0
  28499    16   83209      1105.0                 132.0      -666666666.0
  ...     ...     ...         ...                   ...               ...
  28769    16   83871      1867.0                 783.0           65398.0
  28770    16   83872       709.0                 261.0           94519.0
  28771    16   83873      1671.0                 804.0           37045.0
  28772    16   83874        27.0                  15.0      -666666666.0
  28773    16   83876      1829.0                 672.0           58889.0

         Poverty Count  Poverty Rate  Total Commute Time  Average Commute Time  \
  28495         6330.0     16.438997             16268.0              1.164412
  28496         3256.0     14.334772              8773.0              1.139203
  28497          129.0     46.402878                80.0              0.666667
  28498         4025.0     21.454080              7590.0              1.028595
  28499          127.0     11.493213               469.0              3.553030
  ...              ...           ...                 ...                   ...
  28769           62.0      3.320836               824.0              1.052363
  28770           66.0      9.308886               336.0              1.287356
  28771          316.0     18.910832               739.0              0.919154
  28772            0.0      0.000000                 0.0              0.000000
  28773          259.0     14.160744               661.0              0.983631

         Total Vehicles  Average Vehicles per Household
  28495         14180.0                    1.014960e+00
  28496          7605.0                    9.875341e-01
  28497            80.0                    6.666667e-01
  28498          6505.0                    8.815558e-01
  28499           205.0                    1.553030e+00
  ...               ...                             ...
  28769           750.0                    9.578544e-01
  28770           290.0                    1.111111e+00
  28771           580.0                    7.213930e-01
  28772    -666666666.0                   -4.444444e+07
  28773           575.0                    8.556548e-01

  [278 rows x 11 columns],
        State Zipcode  Population  Number of Households  Household Income  \
  20057    30   59001      1558.0                 734.0           58482.0
  20058    30   59002       127.0                  47.0           37917.0
  20059    30   59003      1359.0                 433.0           46838.0
  20060    30   59006      1461.0                 518.0           44750.0
  20061    30   59007       172.0                  66.0          105625.0
  ...     ...     ...         ...                   ...               ...
  20413    30   59933        97.0                  23.0           46103.0
  20414    30   59934       476.0                 225.0           33482.0
  20415    30   59935      3560.0                1458.0           38750.0
  20416    30   59936       431.0                 132.0           50278.0
  20417    30   59937     13943.0                5830.0           63030.0

         Poverty Count  Poverty Rate  Total Commute Time  Average Commute Time  \
  20057           14.0      0.898588               679.0              0.925068
  20058           33.0     25.984252                52.0              1.106383
  20059          362.0     26.637233               490.0              1.131640
  20060          377.0     25.804244               543.0              1.048263
  20061           13.0      7.558140                72.0              1.090909
  ...              ...           ...                 ...                   ...
  20413           16.0     16.494845                55.0              2.391304
  20414           51.0     10.714286               122.0              0.542222
  20415          546.0     15.337079              1349.0              0.925240
  20416          116.0     26.914153               130.0              0.984848
  20417          989.0      7.093165              6550.0              1.123499

         Total Vehicles  Average Vehicles per Household
  20057           545.0                        0.742507
  20058            45.0                        0.957447
  20059           325.0                        0.750577
  20060           485.0                        0.936293
  20061            65.0                        0.984848
  ...               ...                             ...
  20413             NaN                             NaN
  20414           110.0                        0.488889
  20415          1140.0                        0.781893
  20416           100.0                        0.757576
  20417          5670.0                        0.972556

  [361 rows x 11 columns],
        State Zipcode  Population  Number of Households  Household Income  \
  29835    32   89001      1363.0                 544.0           60152.0
  29836    32   89002     35881.0               12139.0           82778.0
  29837    32   89003       820.0                 471.0      -666666666.0
  29838    32   89004       326.0                 129.0           75515.0
  29839    32   89005     15840.0                6615.0           61787.0
  ...     ...     ...         ...                   ...               ...
  30005    32   89832      1312.0                 488.0           35875.0
  30006    32   89833       137.0                  52.0           42917.0
  30007    32   89834       152.0                  41.0      -666666666.0
  30008    32   89835      1626.0                 644.0           50000.0
  30009    32   89883      4381.0                1265.0           64315.0

         Poverty Count  Poverty Rate  Total Commute Time  Average Commute Time  \
  29835            6.0      0.440205               466.0              0.856618
  29836         2264.0      6.309746             15927.0              1.312052
  29837          163.0     19.878049               373.0              0.791932
  29838           41.0     12.576687                93.0              0.720930
  29839         1429.0      9.021465              6012.0              0.908844
  ...              ...           ...                 ...                   ...
  30005          467.0     35.594512               451.0              0.924180
  30006           44.0     32.116788                62.0              1.192308
  30007           86.0     56.578947                57.0              1.390244
  30008          119.0      7.318573               592.0              0.919255
  30009          581.0     13.261812              2142.0              1.693281

         Total Vehicles  Average Vehicles per Household
  29835           380.0                        0.698529
  29836         14700.0                        1.210973
  29837           270.0                        0.573248
  29838            95.0                        0.736434
  29839          5275.0                        0.797430
  ...               ...                             ...
  30005           385.0                        0.788934
  30006            40.0                        0.769231
  30007             NaN                             NaN
  30008           470.0                        0.729814
  30009          1995.0                        1.577075

  [175 rows x 11 columns],
        State Zipcode  Population  Number of Households  Household Income  \
  29467    35   87001      3639.0                 874.0           40093.0
  29468    35   87002     21993.0                8318.0           42925.0
  29469    35   87004     11673.0                4254.0           46026.0
  29470    35   87005       219.0                 145.0            9076.0
  29471    35   87006      1549.0                 276.0           55543.0
  ...     ...     ...         ...                   ...               ...
  29830    35   88430        98.0                  56.0           49000.0
  29831    35   88431        55.0                   9.0      -666666666.0
  29832    35   88434       469.0                 158.0           53036.0
  29833    35   88435      3707.0                1048.0           30487.0
  29834    35   88436        66.0                  49.0      -666666666.0

         Poverty Count  Poverty Rate  Total Commute Time  Average Commute Time  \
  29467         1036.0     28.469360              1088.0              1.244851
  29468         3807.0     17.310053              7567.0              0.909714
  29469         2121.0     18.170136              4225.0              0.993183
  29470          115.0     52.511416                89.0              0.613793
  29471          250.0     16.139445               594.0              2.152174
  ...              ...           ...                 ...                   ...
  29830            0.0      0.000000                49.0              0.875000
  29831            0.0      0.000000                14.0              1.555556
  29832           31.0      6.609808               219.0              1.386076
  29833          400.0     10.790397              1076.0              1.026718
  29834            0.0      0.000000                26.0              0.530612

         Total Vehicles  Average Vehicles per Household
  29467           975.0                        1.115561
  29468          6730.0                        0.809089
  29469          3795.0                        0.892102
  29470             NaN                             NaN
  29471           460.0                        1.666667
  ...               ...                             ...
  29830            50.0                        0.892857
  29831             NaN                             NaN
  29832           165.0                        1.044304
  29833           980.0                        0.935115
  29834             NaN                             NaN

  [368 rows x 11 columns],
        State Zipcode  Population  Number of Households  Household Income  \
  31867    41   97001       338.0                  69.0           33558.0
  31868    41   97002      6657.0                2413.0           81866.0
  31869    41   97004      4241.0                1707.0           93203.0
  31870    41   97005     26329.0               11286.0           50932.0
  31871    41   97006     74070.0               27222.0           78919.0
  ...     ...     ...         ...                   ...               ...
  32279    41   97911        69.0                  46.0           50278.0
  32280    41   97913      4875.0                1778.0           44712.0
  32281    41   97914     19400.0                5948.0           42517.0
  32282    41   97918      4224.0                1555.0           42434.0
  32283    41   97920        73.0                  57.0      -666666666.0

         Poverty Count  Poverty Rate  Total Commute Time  Average Commute Time  \
  31867          107.0     31.656805                52.0              0.753623
  31868          282.0      4.236142              2866.0              1.187733
  31869          216.0      5.093138              1587.0              0.929701
  31870         5055.0     19.199362             13604.0              1.205387
  31871         7697.0     10.391522             37467.0              1.376350
  ...              ...           ...                 ...                   ...
  32279            7.0     10.144928                30.0              0.652174
  32280          857.0     17.579487              1777.0              0.999438
  32281         3767.0     19.417526              6162.0              1.035978
  32282          742.0     17.566288              1640.0              1.054662
  32283           50.0     68.493151                18.0              0.315789

         Total Vehicles  Average Vehicles per Household
  31867             NaN                             NaN
  31868          2460.0                        1.019478
  31869          1465.0                        0.858231
  31870          9600.0                        0.850611
  31871         29025.0                        1.066233

AttributeError: 'list' object has no attribute 'head'